update the yaml file

diff --git a/.github/workflows/changelog.yml b/.github/workflows/changelog.yml
--- a/.github/workflows/changelog.yml
+++ b/.github/workflows/changelog.yml
@@ -50,53 +50,53 @@ jobs:
       - name: files
         run: |
           ls -l
-#      - name: Ensure no changes to the CHANGELOG.md or CHANGELOG-API.md
-#        if: ${{ !contains(github.event.pull_request.labels.*.name, 'dependencies') && !contains(github.event.pull_request.labels.*.name, 'Skip Changelog') && !contains(github.event.pull_request.title, '[chore]')}}
-#        run: |
-#          if [[ $(git diff --name-only $(git merge-base origin/main $PR_HEAD) $PR_HEAD ./CHANGELOG*.md) ]]
-#          then
-#            echo "CHANGELOG.md and CHANGELOG-API.md should not be directly modified."
-#            echo "Please add a .yaml file to the ./.chloggen/ directory."
-#            echo "See CONTRIBUTING.md for more details."
-#            echo "Alternately, add either \"[chore]\" to the title of the pull request or add the \"Skip Changelog\" label if this job should be skipped."
-#            false
-#          else
-#            echo "CHANGELOG.md and CHANGELOG-API.md were not modified."
-#          fi
+      - name: Ensure no changes to the CHANGELOG.md or CHANGELOG-API.md
+        if: ${{ !contains(github.event.pull_request.labels.*.name, 'dependencies') && !contains(github.event.pull_request.labels.*.name, 'Skip Changelog') && !contains(github.event.pull_request.title, '[chore]')}}
+        run: |
+          if [[ $(git diff --name-only $(git merge-base origin/main $PR_HEAD) $PR_HEAD ./CHANGELOG*.md) ]]
+          then
+            echo "CHANGELOG.md and CHANGELOG-API.md should not be directly modified."
+            echo "Please add a .yaml file to the ./.chloggen/ directory."
+            echo "See CONTRIBUTING.md for more details."
+            echo "Alternately, add either \"[chore]\" to the title of the pull request or add the \"Skip Changelog\" label if this job should be skipped."
+            false
+          else
+            echo "CHANGELOG.md and CHANGELOG-API.md were not modified."
+          fi
 
 
-#      - name: Ensure ./.chloggen/*.yaml addition(s)
-#        if: ${{ !contains(github.event.pull_request.labels.*.name, 'dependencies') && !contains(github.event.pull_request.labels.*.name, 'Skip Changelog') && !contains(github.event.pull_request.title, '[chore]')}}
-#        run: |
-#          if [[ 1 -gt $(git diff --diff-filter=A --name-only $(git merge-base origin/main $PR_HEAD) $PR_HEAD ./.chloggen | grep -c \\.yaml) ]]
-#          then
-#            echo "No changelog entry was added to the ./.chloggen/ directory."
-#            echo "Please add a .yaml file to the ./.chloggen/ directory."
-#            echo "See CONTRIBUTING.md for more details."
-#            echo "Alternately, add either \"[chore]\" to the title of the pull request or add the \"Skip Changelog\" label if this job should be skipped."
-#            false
-#          else
-#            echo "A changelog entry was added to the ./.chloggen/ directory."
-#          fi
+      - name: Ensure ./.chloggen/*.yaml addition(s)
+        if: ${{ !contains(github.event.pull_request.labels.*.name, 'dependencies') && !contains(github.event.pull_request.labels.*.name, 'Skip Changelog') && !contains(github.event.pull_request.title, '[chore]')}}
+        run: |
+          if [[ 1 -gt $(git diff --diff-filter=A --name-only $(git merge-base origin/main $PR_HEAD) $PR_HEAD ./.chloggen | grep -c \\.yaml) ]]
+          then
+            echo "No changelog entry was added to the ./.chloggen/ directory."
+            echo "Please add a .yaml file to the ./.chloggen/ directory."
+            echo "See CONTRIBUTING.md for more details."
+            echo "Alternately, add either \"[chore]\" to the title of the pull request or add the \"Skip Changelog\" label if this job should be skipped."
+            false
+          else
+            echo "A changelog entry was added to the ./.chloggen/ directory."
+          fi
 
-#      - name: Validate ./.chloggen/*.yaml changes
-#        run: |
-#          make chlog-validate \
-#            || { echo "New ./.chloggen/*.yaml file failed validation."; exit 1; }
+      - name: Validate ./.chloggen/*.yaml changes
+        run: |
+          make chlog-validate \
+            || { echo "New ./.chloggen/*.yaml file failed validation."; exit 1; }
 
 
-      # In order to validate any links in the yaml file, render the config to markdown
-#      - name: Render .chloggen changelog entries
-#        if: ${{ !contains(github.event.pull_request.labels.*.name, 'dependencies') && !contains(github.event.pull_request.labels.*.name, 'Skip Changelog') && !contains(github.event.pull_request.title, '[chore]')}}
-#        run: make chlog-preview > changelog_preview.md
-#      - name: Install markdown-link-check
-#        if: ${{ !contains(github.event.pull_request.labels.*.name, 'dependencies') && !contains(github.event.pull_request.labels.*.name, 'Skip Changelog') && !contains(github.event.pull_request.title, '[chore]')}}
-#        run: npm install -g markdown-link-check
-#      - name: Run markdown-link-check
-#        if: ${{ !contains(github.event.pull_request.labels.*.name, 'dependencies') && !contains(github.event.pull_request.labels.*.name, 'Skip Changelog') && !contains(github.event.pull_request.title, '[chore]')}}
-#        run: |
-#          markdown-link-check \
-#            --verbose \
-#            --config .github/workflows/check_links_config.json \
-#            changelog_preview.md \
-#            || { echo "Check that anchor links are lowercase"; exit 1; }
+#       In order to validate any links in the yaml file, render the config to markdown
+      - name: Render .chloggen changelog entries
+        if: ${{ !contains(github.event.pull_request.labels.*.name, 'dependencies') && !contains(github.event.pull_request.labels.*.name, 'Skip Changelog') && !contains(github.event.pull_request.title, '[chore]')}}
+        run: make chlog-preview > changelog_preview.md
+      - name: Install markdown-link-check
+        if: ${{ !contains(github.event.pull_request.labels.*.name, 'dependencies') && !contains(github.event.pull_request.labels.*.name, 'Skip Changelog') && !contains(github.event.pull_request.title, '[chore]')}}
+        run: npm install -g markdown-link-check
+      - name: Run markdown-link-check
+        if: ${{ !contains(github.event.pull_request.labels.*.name, 'dependencies') && !contains(github.event.pull_request.labels.*.name, 'Skip Changelog') && !contains(github.event.pull_request.title, '[chore]')}}
+        run: |
+          markdown-link-check \
+            --verbose \
+            --config .github/workflows/check_links_config.json \
+            changelog_preview.md \
+            || { echo "Check that anchor links are lowercase"; exit 1; }
