changes at main

diff --git a/.github/workflows/changelog.yml b/.github/workflows/changelog.yml
--- a/.github/workflows/changelog.yml
+++ b/.github/workflows/changelog.yml
@@ -76,7 +76,9 @@ jobs:
           fi
 
       - name: Validate ./.chloggen/*.yaml changes
-        run: |
+        run: | 
+          make chlog-new \
+            || { echo "New ./.chloggen/*.yaml file failed validation."; exit 1; }
           make chlog-validate \
             || { echo "New ./.chloggen/*.yaml file failed validation."; exit 1; }
 
